 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ports", type: :request do
  
  # Port. As you add validations to Port, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Port.create! valid_attributes
      get ports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      port = Port.create! valid_attributes
      get port_url(port)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_port_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      port = Port.create! valid_attributes
      get edit_port_url(port)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Port" do
        expect {
          post ports_url, params: { port: valid_attributes }
        }.to change(Port, :count).by(1)
      end

      it "redirects to the created port" do
        post ports_url, params: { port: valid_attributes }
        expect(response).to redirect_to(port_url(Port.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Port" do
        expect {
          post ports_url, params: { port: invalid_attributes }
        }.to change(Port, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ports_url, params: { port: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested port" do
        port = Port.create! valid_attributes
        patch port_url(port), params: { port: new_attributes }
        port.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the port" do
        port = Port.create! valid_attributes
        patch port_url(port), params: { port: new_attributes }
        port.reload
        expect(response).to redirect_to(port_url(port))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        port = Port.create! valid_attributes
        patch port_url(port), params: { port: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested port" do
      port = Port.create! valid_attributes
      expect {
        delete port_url(port)
      }.to change(Port, :count).by(-1)
    end

    it "redirects to the ports list" do
      port = Port.create! valid_attributes
      delete port_url(port)
      expect(response).to redirect_to(ports_url)
    end
  end
end
