 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ships", type: :request do
  
  # Ship. As you add validations to Ship, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ship.create! valid_attributes
      get ships_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ship = Ship.create! valid_attributes
      get ship_url(ship)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ship_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ship = Ship.create! valid_attributes
      get edit_ship_url(ship)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ship" do
        expect {
          post ships_url, params: { ship: valid_attributes }
        }.to change(Ship, :count).by(1)
      end

      it "redirects to the created ship" do
        post ships_url, params: { ship: valid_attributes }
        expect(response).to redirect_to(ship_url(Ship.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ship" do
        expect {
          post ships_url, params: { ship: invalid_attributes }
        }.to change(Ship, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ships_url, params: { ship: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ship" do
        ship = Ship.create! valid_attributes
        patch ship_url(ship), params: { ship: new_attributes }
        ship.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ship" do
        ship = Ship.create! valid_attributes
        patch ship_url(ship), params: { ship: new_attributes }
        ship.reload
        expect(response).to redirect_to(ship_url(ship))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ship = Ship.create! valid_attributes
        patch ship_url(ship), params: { ship: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ship" do
      ship = Ship.create! valid_attributes
      expect {
        delete ship_url(ship)
      }.to change(Ship, :count).by(-1)
    end

    it "redirects to the ships list" do
      ship = Ship.create! valid_attributes
      delete ship_url(ship)
      expect(response).to redirect_to(ships_url)
    end
  end
end
